// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbrxrhjveezxtfwvialj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicnhyaGp2ZWV6eHRmd3ZpYWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxOTE3NTIsImV4cCI6MjA4OTc2Nzc1Mn0.rMOeeYR_2pHCypYm4gISqHkeV7ZxW8_ReTQC12uBWjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});